import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

const context = readFileSync(new URL('../../src/contexts/RecordingStateContext.tsx', import.meta.url), 'utf8');
const flowBarWindow = readFileSync(new URL('../../src/components/hush/FlowBarWindow.tsx', import.meta.url), 'utf8');
const nativeSource = readFileSync(new URL('../../src-tauri/src/lib.rs', import.meta.url), 'utf8');
const flowSettings = readFileSync(new URL('../../src/components/hush/FlowSettings.tsx', import.meta.url), 'utf8');
const shortcutRuntime = readFileSync(new URL('../../src/components/hush/ShortcutRuntime.tsx', import.meta.url), 'utf8');
const recordingStop = readFileSync(new URL('../../src/hooks/useRecordingStop.ts', import.meta.url), 'utf8');

test('native Flow Bar synchronizes backend recording state in its separate WebView', () => {
  assert.match(context, /syncNow:\s*\(\)\s*=>\s*Promise<void>/);
  assert.match(context, /syncNow:\s*syncWithBackend/);
  assert.match(flowBarWindow, /const \{ setStatus, syncNow \} = useRecordingState\(\)/);
  assert.match(flowBarWindow, /setInterval\(\(\) => void syncNow\(\), 500\)/);
  assert.match(flowBarWindow, /hush-onboarding-completed/);
  assert.match(flowBarWindow, /flowBarWindow\.show\(\)/);
  const flowBar = readFileSync(new URL('../../src/components/hush/FlowBar.tsx', import.meta.url), 'utf8');
  assert.match(flowBar, /emitTo\('main', eventName/);
  assert.match(flowBar, /emitToMainWithFallback\('hush-flow-bar-error'/);
  assert.match(flowBar, /if \(isRecording \|\| isBusy\) return/);
  assert.match(flowBar, /Dictation in progress; use Stop or Cancel/);
  assert.match(flowBar, /startDragging\(\)/);
  assert.match(flowBar, /target\?\.closest\('button'\)/);
  assert.match(flowBar, /request-recording-cancel/);
  assert.match(flowBar, /event\.key !== 'Escape'/);
  assert.match(flowBar, /Flow Bar microphone/);
  assert.match(flowBar, /Flow Bar dictation language/);
  assert.match(flowBar, /Copy last dictation/);
  assert.match(flowBar, /navigator\.clipboard\.writeText\(transcript\)/);
  assert.match(flowBarWindow, /hush-flow-bar-disabled/);
  assert.match(flowBarWindow, /currentMonitor\(\)/);
  assert.match(flowBarWindow, /setPosition\(new PhysicalPosition/);
  assert.ok(((shortcutRuntime.match(/hush-toggle-recording/g) || []).length) >= 2);
  assert.match(recordingStop, /window\.localStorage\.getItem\("hush-insert-at-cursor"\) !== "false"/);
  assert.match(recordingStop, /History needs recovery/);
  assert.match(recordingStop, /deliverTranscriptToFocusedApp\(transcriptText\)[\s\S]*storageService\.saveMeeting/);
  assert.match(nativeSource, /current_monitor\(\)[\s\S]*primary_monitor\(\)/);
  assert.match(nativeSource, /flow_bar_start_recording[\s\S]*validate_transcription_model_ready[\s\S]*default_input_device[\s\S]*capture_focused_app\(\)/);
});
